### ISSUE TITLE
Download sample dataset settigs

### ISSUE THREAD

**Issue by jpylvanainen** [guijacquemet/CellTracksColab#11]
In cell 1.2. Compile your data or load existing dataframes, the "Use_test_dataset:" is ticked by default. This causes the user to accidentally download the test dataset. I suggest changing this option to be unticked by default. 

I can also change this once the notebooks have been merged.

**Comment by esgomezm** [comment]
Sure! Go ahead!! Jut check that the cell outputs are removed and that the changes are on dev-egm

Thank you!!

**Comment by jpylvanainen** [comment]
On it now

**Comment by jpylvanainen** [comment]
done

**Comment by jpylvanainen** [comment]
Changes done to TrackMate and custom notebooks. All other notebooks checked and ok.
