### ISSUE TITLE
unclear/unnecessary CallTracksColab_TrackMate prints in Part 2. Visualise your tracks

### ISSUE THREAD

**Issue by jpylvanainen** [guijacquemet/CellTracksColab#12]
2.1 Visualise your tracks in each field of view
2.2 Origin-Normalized Plot for each field of view
- after test visualization (step1) the notebook prints text: <function __main__.<lambda>(filename)>. It is unclear what this means. 

2.3 Origin-Normalized Plot for each condition and repeat
- after test visualization (step1) the notebook prints unclear/unnecessary texts: 
<function __main__.<lambda>(condition, repeat)>
<Figure size 640x480 with 0 Axes>

2.4 Origin-Normalized Plot for each condition
- after test visualization (step1) the notebook prints unclear/unnecessary texts: 
Plot saved as Condition_CTRL_All_Repeat.pdf in /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
<function __main__.<lambda>(condition)>
<Figure size 640x480 with 0 Axes>
-step 2 (process all files), unnecessary outputs. 
Plot saved as Condition_CTRL_All_Repeat.pdf in /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
Plot saved as Condition_CTRL - collagen_All_Repeat.pdf in /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
Plot saved as Condition_MYO10_All_Repeat.pdf in /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
Plot saved as Condition_MYO10  - collagen_All_Repeat.pdf in /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
All plots saved in: /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/
<Figure size 640x480 with 0 Axes>

I recommend instead as in previous processing steps:  "All plots saved in: /content/drive/Shareddrives/CellTracksColab/temp_results/Tracks/"

2.5 Plot the migration vectors for each field of view
- after test visualization (step1) the notebook prints text: <function __main__.<lambda>(filename, display_plots)>. It is unclear what this means.

**Comment by esgomezm** [comment]
Hi @jpylvanainen was this one solved? shall I take it a look?

**Comment by jpylvanainen** [comment]
> Hi @jpylvanainen was this one solved? shall I take it a look?

Hey @esgomezm, Guillaume mentioned that most of the printed lines cannot be removed, they are generated by the libraries we use. But in case you want to take a look, please do :)

**Comment by esgomezm** [comment]
Done! it's the output of calling a function. In this case, it is the lambda function that is being called all the time in a sort of loop with the interact. By adding ";" at the end, the message is hidden.
