### ISSUE TITLE
Plot track parameters (entire dataset) and balanced graph x-titles are overlapping with the result

### ISSUE THREAD

**Issue by jpylvanainen** [guijacquemet/CellTracksColab#21]
Plot track parameters (entire dataset) and balanced graph x-titles are overlapping with the image (bottom right)

![image](https://github.com/CellMigrationLab/CellTracksColab/assets/74545655/3f38336c-8fc2-4182-b828-599781f86ec4)

**Comment by guijacquemet** [comment]
Should be fixed
