### ISSUE TITLE
_Dimensionality_Reduction not running past 3.6

### ISSUE THREAD

**Issue by HGrobe** [guijacquemet/CellTracksColab#24]
Tested the _Dimensionality_Reduction notebook locally and get the error 'list' object has no attribute 'items'. Joanna tested in Colab and got the same error. 

![image](https://github.com/CellMigrationLab/CellTracksColab/assets/158022513/f66643bd-6e93-4240-92d3-9213c405573a)

**Comment by HGrobe** [comment]
@guijacquemet - can't assign so going with @

**Comment by guijacquemet** [comment]
Thanks, this should now be fixed !
