### ISSUE TITLE
Dimension reduction notebook - unnecessary dialog box?

### ISSUE THREAD

**Issue by jpylvanainen** [guijacquemet/CellTracksColab#25]
@guijacquemet Can we remove this empty box which asks to copy-paste the mertics?

![image](https://github.com/CellMigrationLab/CellTracksColab/assets/74545655/42bc9e50-22b3-453d-a653-bea8c6ea6213)

**Comment by guijacquemet** [comment]
Why?
This box enhances reproducibility. You can easily copy and paste previously selected parameters without having to manually tick and untick boxes. This feature is especially useful when working with numerous metrics.

**Comment by jpylvanainen** [comment]
Right, that makes sense. Maybe we can "or" between the cell and the tick boxes? Can input be from both the cell and tick boxes (for whatever reason).

**Comment by guijacquemet** [comment]
It can be from both :) 
If you add the names it dynamically untick the boxes not in the dialogue window. You can then tick some more if you want

**Comment by jpylvanainen** [comment]
oh cool! didn't think to test that :D
