### ISSUE TITLE
xml file problem comparable to issue #31

### ISSUE THREAD

**Issue by fabricesenger** [guijacquemet/CellTracksColab#34]
I try to run the software locally, it worked fine for the demo data 

hereafter the cell with path to data and results 

#@markdown ##Provide the path to your dataset:

#@markdown ###You have multiple tracking files you want to compile, provide the path to your:

Folder_path = r'C:\Users\fabri\Documents\Celltrackscollab_test\Experiments\Condition_1\R1'
Data_Dims = "2D" #@param ["2D", "3D"]
File_Format = "xml" #@param ["csv", "xml"]
Data_Type = "TrackMate Files"

#@markdown ###Or use a test dataset (up to 10 min download)
#@markdownUse_test_dataset = False #@param {type:"boolean"}

#@markdown ###Provide the path to your Result folder

Results_Folder = r'C:\Users\fabri\Documents\Celltrackscollab_test\Results'

CellTracks.Folder_path = Folder_path

CellTracks.Results_Folder = Results_Folder
CellTracks.skiprows = None
CellTracks.data_type = Data_Type
CellTracks.data_dims = Data_Dims
CellTracks.file_format = File_Format

# Load data
CellTracks.LoadTrackingData()

merged_spots_df = CellTracks.spots_data
check_for_nans(merged_spots_df, "merged_spots_df")
merged_tracks_df = CellTracks.tracks_data
if Data_Dims == '2D':
  merged_spots_df['POSITION_Z'] = 0

CellTracks.dim_mapping

print("...Done")

Here the errors i got, mainly from data loader 

ValueError                                Traceback (most recent call last)
Cell In[16], line 27
     24 CellTracks.file_format = File_Format
     26 # Load data
---> 27 CellTracks.LoadTrackingData()
     29 merged_spots_df = CellTracks.spots_data
     30 check_for_nans(merged_spots_df, "merged_spots_df")

File [~\CellTracksColab-main\CellTracksColab-main\Notebook\..\celltracks\data_loader.py:667](http://localhost:8888/lab/tree/Notebook/~/CellTracksColab-main/CellTracksColab-main/celltracks/data_loader.py#line=666), in TrackingData.LoadTrackingData(self)
    663     self.__load_trackmate_csv__()
    665 elif self.data_type == "TrackMate Files" and self.file_format.__contains__("xml"):
--> 667     self.__load_trackmate_xml__()
    669 elif self.data_type == "Custom" and self.file_format.__contains__("csv"):
    671     self.__load_csv__()

File [~\CellTracksColab-main\CellTracksColab-main\Notebook\..\celltracks\data_loader.py:545](http://localhost:8888/lab/tree/Notebook/~/CellTracksColab-main/CellTracksColab-main/celltracks/data_loader.py#line=544), in TrackingData.__load_trackmate_xml__(self)
    542 def __load_trackmate_xml__(self):
    543 
    544     # Load Tracking data in memory
--> 545     merged_spots_df, merged_tracks_df = load_and_populate_from_TM_XML(self.Folder_path)
    547     print(f"Tracking data loaded in memory.")
    549     if not validate_tracks_df(merged_tracks_df):

File [~\CellTracksColab-main\CellTracksColab-main\Notebook\..\celltracks\xml_loader.py:469](http://localhost:8888/lab/tree/Notebook/~/CellTracksColab-main/CellTracksColab-main/celltracks/xml_loader.py#line=468), in load_and_populate_from_TM_XML(folder_path)
    466     track_dfs.append(track_df)
    468 # Creating the final dataframes.
--> 469 merged_spots_df = pd.concat(spot_dfs, ignore_index=True)
    470 merged_tracks_df = pd.concat(track_dfs, ignore_index=True)
    471 check_calibration(units_list)

File [~\.conda\envs\celltrackscolab\lib\site-packages\pandas\util\_decorators.py:331](http://localhost:8888/lab/tree/Notebook/~/.conda/envs/celltrackscolab/lib/site-packages/pandas/util/_decorators.py#line=330), in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File [~\.conda\envs\celltrackscolab\lib\site-packages\pandas\core\reshape\concat.py:368](http://localhost:8888/lab/tree/Notebook/~/.conda/envs/celltrackscolab/lib/site-packages/pandas/core/reshape/concat.py#line=367), in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    146 @deprecate_nonkeyword_arguments(version=None, allowed_args=["objs"])
    147 def concat(
    148     objs: Iterable[NDFrame] | Mapping[HashableT, NDFrame],
   (...)
    157     copy: bool = True,
    158 ) -> DataFrame | Series:
    159     """
    160     Concatenate pandas objects along a particular axis.
    161 
   (...)
    366     1   3   4
    367     """
--> 368     op = _Concatenator(
    369         objs,
    370         axis=axis,
    371         ignore_index=ignore_index,
    372         join=join,
    373         keys=keys,
    374         levels=levels,
    375         names=names,
    376         verify_integrity=verify_integrity,
    377         copy=copy,
    378         sort=sort,
    379     )
    381     return op.get_result()

File [~\.conda\envs\celltrackscolab\lib\site-packages\pandas\core\reshape\concat.py:425](http://localhost:8888/lab/tree/Notebook/~/.conda/envs/celltrackscolab/lib/site-packages/pandas/core/reshape/concat.py#line=424), in _Concatenator.__init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    422     objs = list(objs)
    424 if len(objs) == 0:
--> 425     raise ValueError("No objects to concatenate")
    427 if keys is None:
    428     objs = list(com.not_none(*objs))

ValueError: No objects to concatenate

**Comment by fabricesenger** [comment]
If needed i might send you the xml file, just to make sure it works in your hands

**Comment by HGrobe** [comment]
Hi Fabrice, 

I tested the current Trackmate notebook on my end, with my own data and it runs. One thing I noticed in your message was a weird "r" in front of the paths (Folder_path = **r'**C:\Users\fabri\Documents\Celltrackscollab_test\Experiments\Condition_1\R1'). If that's not it, please send your data so I can have a closer look.

**Comment by fabricesenger** [comment]
Hello, 

yes, i slightly modified the code. 
After testing the downloadable example data (wich worked, as the results have been saved to my results folder), i removed the option to further use the example data set. 
For the path, i used the "r" so that my windows path gets read as a in python... 
For the time being I'm just struggling with my FIJI and Trackmate so i do a clean install to solve that issue. 

Besides that you can find the files under the following link : 

[ https://filesender.renater.fr/?s=download&token=baa5f8f9-6ae7-4ddd-a090-2f619e037764 | https://filesender.renater.fr/?s=download&token=baa5f8f9-6ae7-4ddd-a090-2f619e037764 ] 

Thank you very much for your time and efforts, 

Fabrice 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Novembre 2024 15:01:12 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hi Fabrice, 

I tested the current Trackmate notebook on my end, with my own data and it runs. One thing I noticed in your message was a weird "r" in front of the paths (Folder_path = **r'**C:\Users\fabri\Documents\Celltrackscollab_test\Experiments\Condition_1\R1'). If that's not it, please send your data so I can have a closer look.

**Comment by HGrobe** [comment]
Hi, 

Thanks for the clarification, I wasn't familiar with the "r" trick... In any case, I downloaded your data and have a look. We did run into some issues after the latest TrackMate update, so that might be it. 
I'll let you know as soon as I have a better idea of what's going on. :)

**Comment by HGrobe** [comment]
Hi!

So I tested the Trackmate notebook with the data you provided and also ran into issues (even though not the exact same as you). At least in the files you provided only one of them is a full Trackmate file ("FOV1.xml"). The other seems to be a Track export saved as an xml which leads to the issue I'm seeing. Can you quickly check on your end that all the files you want to load are in fact Trackmate files? 
Because if I delete the "Tracks.xml" file from the folder the notebook runs.

**Comment by fabricesenger** [comment]
Hello,  
Sounds good. Today is a French holiday and I'm of the lab. I will check probably by tomorrow and let you know. Thank you  
 
  
 
 
 

-----Message original-----

De: Hanna ***@***.***>
à: CellMigrationLab ***@***.***>
Cc: fabricesenger ***@***.***>; Author ***@***.***>
Envoyé: lundi 11 novembre 2024 09:12 CET
Sujet : Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34)

 

  Hi! So I tested the Trackmate notebook with the data you provided and also ran into issues (even though not the exact same as you). At least in the files you provided only one of them is a full Trackmate file ("FOV1.xml"). The other seems to be a Track export saved as an xml which leads to the issue I'm seeing. Can you quickly check on your end that all the files you want to load are in fact Trackmate files?
Because if I delete the "Tracks.xml" file from the folder the notebook runs. —

**Comment by fabricesenger** [comment]
Hello, 

by the way, would you mind to share a screenshot with me so i will use exactly the same config, i.e; , path etc, without the little "r" thingy ... to be as comparable as possible to what you did ? 

Best, 

Fabrice 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 11 Novembre 2024 09:12:40 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hi! 

So I tested the Trackmate notebook with the data you provided and also ran into issues (even though not the exact same as you). At least in the files you provided only one of them is a full Trackmate file ("FOV1.xml"). The other seems to be a Track export saved as an xml which leads to the issue I'm seeing. Can you quickly check on your end that all the files you want to load are in fact Trackmate files? 
Because if I delete the "Tracks.xml" file from the folder the notebook runs.

**Comment by fabricesenger** [comment]
Dear Hanna, 

I deleted and re-installed my env ... next I ran the sample data provided and everything worked like a charm. Of note, I changed the \ to / manually to not introduce the fancy "r" thus, even with the provided sample data everything produced by the notebook got saved into my Results folder. 
Next I tried with my own data. 
To do so, I used the Trackmate Batcher and went for csv instead of xml , the files are then loaded without problem as demonstrated by the file structure(wich is tested by the notebook). 
Unfortunatly, my files were empty, as if no track data has been saved , i.e., just the file structure without data. 
I have an older version of trackmate ( in a zipped FIJI archive), i will give it a try and let you know. 

Once more thank you for help and support, 

Fabrice. 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 11 Novembre 2024 09:12:40 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hi! 

So I tested the Trackmate notebook with the data you provided and also ran into issues (even though not the exact same as you). At least in the files you provided only one of them is a full Trackmate file ("FOV1.xml"). The other seems to be a Track export saved as an xml which leads to the issue I'm seeing. Can you quickly check on your end that all the files you want to load are in fact Trackmate files? 
Because if I delete the "Tracks.xml" file from the folder the notebook runs.

**Comment by HGrobe** [comment]
Hey Fabrice, 

good idea about exporting the data as csv, that would have been my next suggestion ;) 

Here is what is running for me with your data, using only the FOV1.xml file:

<img width="471" alt="2024-11-13_09h14_44" src="https://github.com/user-attachments/assets/725a9785-2f72-4a70-9902-1f4ea8a3d617">

![2024-11-13_09h17_48](https://github.com/user-attachments/assets/242d3196-5cf0-429b-8cd1-f955cf826892)

And I checked the output, there is data both in the 'merged_Tracks.csv' and in the 'merged_spots.csv'. So the data is there and can in general be read. Which leaves us with why the heck it's not working with your whole dataset. One idea (and I'm sorry if this sounds dumb and obvious), but did you extract the output 'merged_Tracks.csv' and 'merged_spots.csv' before opening them? The latest version of the notebooks zips these files because they can get quite large and we haven't updated the documentation about it yet. If you didn't the files will look empty. 

If you did, could you send me a few of the input csv files (spots and tracks)? 

Best, Hanna

**Comment by fabricesenger** [comment]
Hello Hanna, 

do you think working on a PC with windows11 may be a problem. 
Just to say I ran allready in some issues like UTF8 and things like that ... 

Nonetheless I will go ahaed with testing on my side 

Fabrice 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 13 Novembre 2024 08:29:02 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hey Fabrice, 

good idea about exporting the data as csv, that would have been my next suggestion ;) 

Here is what is running for me with your data, using only the FOV1.xml file: [ https://github.com/user-attachments/assets/725a9785-2f72-4a70-9902-1f4ea8a3d617 | 2024-11-13_09h14_44.png (view on web) ] 

[ https://github.com/user-attachments/assets/242d3196-5cf0-429b-8cd1-f955cf826892 | 2024-11-13_09h17_48.png (view on web) ] 

And I checked the output, there is data both in the 'merged_Tracks.csv' and in the 'merged_spots.csv'. So the data is there and can in general be read. Which leaves us with why the heck it's not working with your whole dataset. One idea (and I'm sorry if this sounds dumb and obvious), but did you extract the output 'merged_Tracks.csv' and 'merged_spots.csv' before opening them? The latest version of the notebooks zips these files because they can get quite large and we haven't updated the documentation about it yet. If you didn't the files will look empty. 

If you did, could you send me a few of the input csv files (spots and tracks)? 

Best, Hanna

**Comment by HGrobe** [comment]
Hey, 

can't be it, I'm also on Windows11 🫤

**Comment by fabricesenger** [comment]
Any particular settings considering utf8?  
 
  
 
 
 

-----Message original-----

De: Hanna ***@***.***>
à: CellMigrationLab ***@***.***>
Cc: fabricesenger ***@***.***>; Author ***@***.***>
Envoyé: mercredi 13 novembre 2024 17:17 CET
Sujet : Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34)

 

  Hey, can't be it, I'm also on Windows11 🫤 —

**Comment by fabricesenger** [comment]
Hello Hanna, 

finally I made some progress. 
I tried to use the batcher to generate the csv files and somehow it doesn't work in my hands generating weird files with headers but no data ... next I made a new tracking and manually exported the spots and tracks . 
I fed those csv files to celltrackscolab and this is what i got : 
Thus i'm halfway there, difficult though to understand why the spot csv is ok, while the tracks csv looks weird ... particularly with the infinity values and Nan values 

De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 13 Novembre 2024 17:17:43 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 






Hey, 

can't be it, I'm also on Windows11 🫤

**Comment by HGrobe** [comment]
Hey! Glad to hear things are finally moving. So did I understand correctly that the notebook works for you locally when the files come our properly from TrackMate.? 

So we just need to figure out why your TrackMate is not behaving. Can you share one of the weird TrackMate files? We had a few issues with NaN and Infs before and I would like to check if it's the same thing here.

**Comment by fabricesenger** [comment]
Hello, 

indeed it seems my trackmate outputs are strange ... here the csv's : [ https://filesender.renater.fr/?s=download&token=42c5206f-4a4f-4a92-ae0a-61aa41a428e4 | https://filesender.renater.fr/?s=download&token=42c5206f-4a4f-4a92-ae0a-61aa41a428e4 ] 

What i noticed is the strange header. Nonetheless it seems the spots are read in the right way, whereas the tracks show some issues 

I didn't manage to use the batcher , but instead exported the csv files from within Trackmate ... 
At some point I will ask Jean-Yves Tynevez what i might have wrong . 

Thank you again for the time you spend on this 

Fabrice 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Jeudi 14 Novembre 2024 15:34:41 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hey! Glad to hear things are finally moving. So did I understand correctly that the notebook works for you locally when the files come our properly from TrackMate.? 

So we just need to figure out why your TrackMate is not behaving. Can you share one of the weird TrackMate files? We had a few issues with NaN and Infs before and I would like to check if it's the same thing here.

**Comment by HGrobe** [comment]
Hi Fabrice, 

Thanks for the files, I'll have a look. We also have some TrackMate people in our group, I'll ask them as well. If they say something useful I'll let you know :)

**Comment by fabricesenger** [comment]
Hello, 

from all the tests I performed I allways fall back to the issue that the spot files are correctedly handeled by CTC whereas the track files seem somehow corrupted , indeed I checked the generated gz files, and spot file looks good but track file is empty. 

It seems that the exported csv files are correct but in the track file there's something weird. 

To dig deeper into this i might share with you my test data set . It is a movie of a cell monolayer acquired in phase contrast and then segmented with cellpose. 

On your side, do you have any clue about what is going on ? 

Have a nice day, 

Fabrice 


De: "Hanna Grobe" ***@***.***> 
À: "CellMigrationLab/CellTracksColab" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Author" ***@***.***> 
Envoyé: Jeudi 14 Novembre 2024 16:03:48 
Objet: Re: [CellMigrationLab/CellTracksColab] xml file problem comparable to issue #31 (Issue #34) 





Hi Fabrice, 

Thanks for the files, I'll have a look. We also have some TrackMate people in our group, I'll ask them as well. If they say something useful I'll let you know :)

**Comment by fabricesenger** [comment]
Successssss !
Following Jean-Yves suggestion I used the cellpose tracker, now the xml file is OK and celltrackscolab handles it.
Unfortunatly I have to find a way to adjust the cellpose settings in trackmate, by default, my segmentations are rather poor (wich is kind of an unrelated issue)
Have a nice day,
Fabrice
